recipe: drupal9
config:
  php: '7.4'
  composer_version: 1.10.20
  via: 'apache:2.4'
  webroot: web
  database: 'mysql:5.7'
  drush: ^10
  xdebug: true
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
    portforward: 1026
  node:
    type: 'node:14'
    build:
      - cd /app && npm install & npm install -g gulp-cli
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
name: lando-drupal-project
